/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/NewNoteDialog copy.vue')['default']
    EditNoteDialog: typeof import('./src/components/EditNoteDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewNoteDialog: typeof import('./src/components/NewNoteDialog.vue')['default']
    NewNoteView: typeof import('./src/components/NewNoteView.vue')['default']
    Note: typeof import('./src/components/Note.vue')['default']
    NoteNode: typeof import('./src/components/NoteNode.vue')['default']
    NoteView: typeof import('./src/components/NoteView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
